# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\dell\OneDrive\Bureau\Projet Pokémon\RATHANA-BOUCHART-KACZOR\Designer\combat.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(568, 300)
        self.Fond = QtWidgets.QLabel(Dialog)
        self.Fond.setGeometry(QtCore.QRect(0, -10, 571, 331))
        self.Fond.setMaximumSize(QtCore.QSize(571, 16777215))
        self.Fond.setText("")
        self.Fond.setPixmap(QtGui.QPixmap("C:\\Users\\dell\\OneDrive\\Bureau\\Projet Pokémon\\RATHANA-BOUCHART-KACZOR\\Designer\\../../../../../Downloads/combat fond.png"))
        self.Fond.setScaledContents(True)
        self.Fond.setWordWrap(False)
        self.Fond.setObjectName("Fond")
        self.Vie = QtWidgets.QProgressBar(Dialog)
        self.Vie.setEnabled(True)
        self.Vie.setGeometry(QtCore.QRect(450, 210, 118, 23))
        self.Vie.setMouseTracking(False)
        self.Vie.setAccessibleName("")
        self.Vie.setAutoFillBackground(False)
        self.Vie.setStyleSheet("")
        self.Vie.setProperty("value", 23)
        self.Vie.setTextVisible(False)
        self.Vie.setInvertedAppearance(True)
        self.Vie.setObjectName("Vie")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
